"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const LinkedList_1 = require("./Structures/LinkedList");
const Node_1 = require("./Structures/Node");
console.log("Node -------");
const p = new Node_1.Node(1);
const q = new Node_1.Node(2);
p.next = q;
console.log(p.next.data);
console.log("LinkedList -------");
const list = new LinkedList_1.LinkedList();
let last = list.getLastNode();
console.log("get last: ", last === null || last === void 0 ? void 0 : last.data);
console.log("insert data: 3");
list.add({ data: 3 });
last = list.getLastNode();
console.log("get last: ", last === null || last === void 0 ? void 0 : last.data);
console.log("insert node: q", q.data);
list.add({ node: q });
last = list.getLastNode();
console.log("get last: ", last === null || last === void 0 ? void 0 : last.data);
